stock:
  code: "sh601088"
  base_price: 39.0           # 固定的基准价格
  initial_investment: 50000   # 初始投资
  
  # 马丁格尔策略配置
  martingale:
    multiplier: 1.3          # 马丁格尔乘数
    grid_size: 0.03          # 每格3%
    levels: 6                # 6个级别
    stop_loss: 0.29          # 止损位29%
    stop_profit: 0.1         # 止盈位10%
  # 网格策略配置
  grid:
    upper_price: 43.0        # 上边界
    lower_price: 35.0        # 下边界
    grid_size: 0.015          # 每格1.5%
    # grid_count: 6            # 将价格区间分为6格
    amount_per_grid: 100    # 每格股数
    stop_loss_price: 37.90    # 止损位29%
    stop_profit_price: 43.0   # 止盈位10%